var b=t=>e=>{var a=t[e];if(a)return a();throw new Error("Module not found in bundle: "+e)};import z from"https://cdn.jsdelivr.net/npm/highlight.js@11/+esm";var x,f;function P({startTime:t,endTime:e,callback:a}){f={startTime:t,endTime:e,callback:a},requestAnimationFrame(k)}function k(t){if(x!==void 0&&t-x<1e3){requestAnimationFrame(k);return}x=t;let e=new Date;e<f.startTime?f.callback({status:"pending",time:f.startTime-e}):e>f.endTime?f.callback({status:"ended",time:e-f.endTime}):f.callback({status:"running",time:f.endTime-e}),setTimeout(()=>requestAnimationFrame(k),1e3)}var E=t=>{let e=Math.floor(t/864e5),a=Math.floor(t%864e5/36e5),s=Math.floor(t%36e5/6e4),c=Math.floor(t%6e4/1e3),l=h=>String(h).padStart(2,"0");return e>0?`${e}d ${l(a)}:${l(s)}:${l(c)}`:`${l(a)}:${l(s)}:${l(c)}`},w=t=>{let e={weekday:"short",year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"numeric",hour12:!0,timeZoneName:"short"};return t.toLocaleString("en-IN",e)};var Y="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2okOHspNjgA+2rTLbeuYcxiP/hG8C6Sb9iwg3yiLAA4HCnpITcbWCSelbvbYGuc3EbNy4xFyf5Cbj5DHJMIDEkryOgyd2giIIIBOUBj8S63uGcnRpOBh9NFatfNwheKuzsPuVNldu6A9cNteNpXcWyJjG2axVfmq7i6SuKr1JoWYG7xTTAvKPujSl4OtsQfO3h5NepzdfXpr28oNnzfWed+zclR6BcmNNo/WVfJ4xyCLSf0BCOgdTgW6PdaChd1l9VDetJZVEgC5tkyvXsfISI6iyrYbKR0NEBSqq4XkadEjsCs4F1RncsS4LlgniT7GlkL9Mce3b0wGLs9/7ZIXdQIDAQAB";async function R(t){let e=U(Y),a=await crypto.subtle.importKey("spki",e,{name:"RSA-OAEP",hash:"SHA-256"},!1,["encrypt"]),s=new TextEncoder().encode(t),c=await crypto.subtle.encrypt({name:"RSA-OAEP"},a,s),l=new Uint8Array(c);return btoa(String.fromCharCode(...l))}function U(t){let e=atob(t),a=e.length,s=new Uint8Array(a);for(let c=0;c<a;c++)s[c]=e.charCodeAt(c);return s.buffer}async function J(t){let a=new TextEncoder().encode(t),s=await crypto.subtle.digest("SHA-256",a);return Array.from(new Uint8Array(s)).map(h=>h.toString(16).padStart(2,"0")).join("")}import{html as F,render as V}from"https://cdn.jsdelivr.net/npm/lit-html@3/lit-html.js";import X from"https://cdn.jsdelivr.net/npm/jwt-decode@3/build/jwt-decode.esm.js";function G(t){let e=JSON.parse(localStorage.getItem("user")||"null");return e?V(F`
        <div id="logged-in-email" class="mb-3">You are logged in as <strong>${e.email}</strong>.</div>
        <div class="mb-3">
          <button
            class="btn btn-sm btn-outline-danger"
            @click=${()=>{localStorage.removeItem("user"),location.reload()}}
          >
            Logout
          </button>
        </div>
      `,t):(V(F`<div id="googleSignInButton" class="mx-auto" style="max-width: 200px"></div>`,t),google.accounts.id.initialize({client_id:"233761863432-t8g2u6esaeli8o2e2crvnu29u94ukt7k.apps.googleusercontent.com",callback:a=>{e=X(a.credential),localStorage.setItem("user",JSON.stringify(e)),location.reload()}}),google.accounts.id.renderButton(document.getElementById("googleSignInButton"),{theme:"filled_black",size:"large",shape:"pill",logo_alignment:"left"})),e}var Z=b({"./exam-tds-2024-sep-roe1.info.js":()=>import("./exam-tds-2024-sep-roe1.info.js"),"./exam-tds-2025-01-ga1.info.js":()=>import("./exam-tds-2025-01-ga1.info.js"),"./exam-tds-2025-01-ga2.info.js":()=>import("./exam-tds-2025-01-ga2.info.js"),"./exam-tds-2025-01-ga3.info.js":()=>import("./exam-tds-2025-01-ga3.info.js"),"./exam-technical-assessment-2024-11.info.js":()=>import("./exam-technical-assessment-2024-11.info.js")});var _=b({"./exam-tds-2024-sep-roe1.info.js":()=>import("./exam-tds-2024-sep-roe1.info.js"),"./exam-tds-2024-sep-roe1.js":()=>import("./exam-tds-2024-sep-roe1.js"),"./exam-tds-2025-01-ga1.info.js":()=>import("./exam-tds-2025-01-ga1.info.js"),"./exam-tds-2025-01-ga1.js":()=>import("./exam-tds-2025-01-ga1.js"),"./exam-tds-2025-01-ga2.info.js":()=>import("./exam-tds-2025-01-ga2.info.js"),"./exam-tds-2025-01-ga2.js":()=>import("./exam-tds-2025-01-ga2.js"),"./exam-tds-2025-01-ga3.info.js":()=>import("./exam-tds-2025-01-ga3.info.js"),"./exam-tds-2025-01-ga3.js":()=>import("./exam-tds-2025-01-ga3.js"),"./exam-technical-assessment-2024-11.info.js":()=>import("./exam-technical-assessment-2024-11.info.js"),"./exam-technical-assessment-2024-11.js":()=>import("./exam-technical-assessment-2024-11.js")});var S=document.body,I=document.getElementById("countdown"),T=document.getElementById("score"),ee=document.getElementById("login"),L=document.getElementById("notification"),te=document.getElementById("instructions"),i=document.getElementById("exam-form"),B=document.getElementById("loading-questions"),C=document.getElementById("questions"),q=document.querySelectorAll(".check-action"),O=document.querySelectorAll(".save-action"),N=document.getElementById("submission-status"),ne,$,v,j,M,K;async function pe(t){let e;try{e=await Z(`./exam-${t}.info.js`)}catch{i.innerHTML=`
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Error!</h4>
        <p>Sorry, we couldn't find the quiz ${t}. You might have the wrong link.</p>
        <hr>
        <p class="mb-0">Please contact the exam team for assistance.</p>
      </div>`,i.classList.remove("d-none");return}let{title:a,start:s,end:c,admin:l,instructions:h,allowed:n,read:d}=e.default;document.title=a,te.innerHTML=h;let u=new Date(s),g=new Date(c);P({startTime:u,endTime:g,callback:A});let r=G(ee);if(!r||!r.email)return;v=l?l(r.email):!1,navigator.sendBeacon("./log",JSON.stringify({quiz:t,email:r.email}));let y=new URLSearchParams(window.location.search);v&&y.get("email")&&(r.email=y.get("email")),j=v||(n?n(r.email):!0),M=!j&&(d?d(r.email):!1);let p=(o,m)=>`<div class="d-flex align-items-center mt-2">
    <button class="btn btn-sm btn-outline-primary me-2 load-answers" data-bs-toggle="collapse" data-index="${m}">Reload</button>
    from ${new Date(o.time).toLocaleString()}. Score: ${o.total}
  </div>`;j?(await H(t,r),fetch(`./filter?quiz=${t}&email=${r.email}&history=1&limit=3`).then(o=>o.json()).then(({data:o})=>{o.length&&(L.innerHTML=`<div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Recent saves</h4>
            ${o.map(p).join("")}
            </div>`,K=o)})):M?(await H(t,r),L.innerHTML=`<div class="alert alert-info" role="alert">
      <h4 class="alert-heading">Reading only</h4>
      <p>You can read the questions, but you cannot submit your own answers.</p>
    </div>`):(i.innerHTML=`<div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Not authorized</h4>
      <p>${r.email} is not allowed to take this exam.</p>
      <p>Log in as an authorized user or contact the exam team for assistance.</p>
    </div>`,i.classList.remove("d-none")),L.addEventListener("click",o=>{o.target.classList.contains("load-answers")&&(Q(K[o.target.dataset.index].result.answers),o.target.textContent="Loaded",o.target.classList.add("btn-success"),o.target.disabled=!0)});function A({status:o,time:m}){S.dataset.status=v?"admin":o,o=="pending"?I.textContent=m<24*60*60*1e3?`Starts in ${E(m)}`:`Starts ${w(u)}`:o=="ended"?I.textContent=`Ended at ${w(g)}`:o=="running"&&(I.textContent=m<24*60*60*1e3?`${E(m)} left`:`Due ${w(g)}`),$||H(t,r)}}async function H(t,e){if(e&&(S.dataset.status=="running"||S.dataset.status=="admin")&&!$){let a=window.location.hash.slice(1);B.classList.remove("d-none"),a&&B.scrollIntoView({behavior:"smooth",block:"center"}),i.classList.remove("d-none"),$=(await _(`./exam-${t}.js`)).questions;let s;try{s=await $(e,C)}catch(n){C.innerHTML=`<div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Error!</h4>
        <p>Sorry, we couldn't load the questions. That's strange.</p>
        <pre>${n.message}</pre>
        <hr>
        <p class="mb-0">Please contact the exam team for assistance.</p>
      </div>`;return}B.classList.add("d-none"),z.highlightAll(),a?document.getElementById(a).scrollIntoView({behavior:"smooth"}):S.scrollIntoView(),M&&([...q,...O,T].forEach(n=>n.disabled=!0),C.querySelectorAll("input, textarea, button").forEach(n=>n.disabled=!0)),i.querySelectorAll(".form-control").forEach(n=>{n.parentNode.querySelector(".valid-feedback, .invalid-feedback")||n.insertAdjacentHTML("afterend",`<div class="valid-feedback mb-3 comment">Correct!</div>
            <div class="invalid-feedback mb-3 comment">Incorrect. Try again.</div>`)}),[...q,...O,T].forEach(n=>n.classList.remove("d-none")),i.addEventListener("input",async()=>{localStorage.setItem(`exam:${e.email}`,JSON.stringify(Object.fromEntries(new FormData(i))))}),Q(JSON.parse(localStorage.getItem(`exam:${e.email}`)||"{}"));let c=n=>{n.preventDefault(),l()};[...q].forEach(n=>n.addEventListener("click",c)),[...O].forEach(n=>n.addEventListener("click",h)),i.addEventListener("submit",c);async function l(){let n=Object.fromEntries(new FormData(i)),d={},u=0,g=0;for(let[r]of Object.entries(n))i.querySelector(`[data-question="${r}"] .invalid-feedback`).textContent="Checking...",i.querySelector(`[data-question="${r}"] .valid-feedback`).textContent="Checking...";for(let[r,y]of Object.entries(n)){let p=i.querySelector(`[data-question="${r}"]`),A=i.querySelector(`[name="${r}"]`),o=s[r].answer??null,m=!1,D="Incorrect. Try again.";if(typeof o=="function")try{m=await o(y)}catch(W){D=W}else o===null?y&&(m=!0):m=y===o.toString();d[r]=m?s[r].weight:0,u+=d[r],g+=s[r].weight,p.querySelector(".invalid-feedback").textContent=D,p.querySelector(".valid-feedback").textContent="Correct",A.setCustomValidity(m?"":"Incorrect answer"),i.classList.add("was-validated")}return T.textContent=`Score: ${u} / ${g}`,{answers:n,scores:d,total:u,max:g}}async function h(){let n=await l();Object.assign(n,{quiz:t,deadline:ne,email:e.email}),n.signature=await R(await J(JSON.stringify(n))),N.innerHTML='<div class="spinner-border" role="status"></div>',N.scrollIntoView({behavior:"smooth",block:"center"});let d;try{d=await fetch("./submit",{method:"POST",body:JSON.stringify(n)}).then(u=>u.json())}catch(u){d={error:u.message}}N.innerHTML=d.error?`
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Error!</h4>
            <p>${d.error}</p>
            <hr>
            <p class="mb-0">Please contact the exam team for assistance.</p>
          </div>`:`
          <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">${d.data}</h4>
            <p class="mb-0">If you submit again, it will overwrite your previous submission and score.</p>
          </div>`}}}function Q(t){for(let[e,a]of Object.entries(t)){let s=i.querySelector(`[name="${e}"]`);s&&s.type!="file"&&(s.value=a)}}export{pe as setup};