from flask import Flask, request, jsonify
marks_json_lis = [{"name":"zPTkKy9lF","marks":54},{"name":"U8v10s88j","marks":59},{"name":"3k8bH","marks":88},{"name":"cYF1Zlgf","marks":93},{"name":"4zMSn","marks":92},{"name":"OE1","marks":52},{"name":"2OB5dHHDHP","marks":65},{"name":"HZuEX7vhTY","marks":12},{"name":"jTvt5QRh","marks":0},{"name":"s","marks":14},{"name":"2UI","marks":34},{"name":"4Fpxx45","marks":71},{"name":"O","marks":47},{"name":"7Fjo","marks":99},{"name":"ehpelR6l","marks":81},{"name":"O2rJClcc","marks":48},{"name":"8zg1p4r","marks":77},{"name":"In42QvFN","marks":37},{"name":"oscPWCcxf","marks":16},{"name":"IG6zmXaeS","marks":77},{"name":"9kdO6","marks":51},{"name":"LpGdSpKxV","marks":77},{"name":"M1CC","marks":51},{"name":"5","marks":11},{"name":"sHjC","marks":20},{"name":"ol3","marks":0},{"name":"vCbK","marks":48},{"name":"hT","marks":45},{"name":"QMctEya","marks":17},{"name":"7dsG","marks":63},{"name":"A3","marks":99},{"name":"qrB4pk4t","marks":4},{"name":"6FRCN61kZG","marks":30},{"name":"Yid2UOYgPL","marks":68},{"name":"PRl1","marks":12},{"name":"orOo0hxM","marks":56},{"name":"n9","marks":13},{"name":"U2B","marks":47},{"name":"wfh08","marks":17},{"name":"AV","marks":7},{"name":"oro","marks":62},{"name":"GJvWUYH6","marks":49},{"name":"s","marks":31},{"name":"5Do4lm","marks":52},{"name":"5Ra6O9Dm","marks":42},{"name":"0","marks":4},{"name":"70V6FLwF","marks":69},{"name":"pbp9zN0ia","marks":73},{"name":"xNJGsq","marks":10},{"name":"nadn9aZD","marks":19},{"name":"CioE","marks":88},{"name":"Ucj","marks":11},{"name":"xw","marks":60},{"name":"y7kdwVSUQ6","marks":49},{"name":"2kw","marks":61},{"name":"4","marks":13},{"name":"TPS4K2HN","marks":87},{"name":"wTBN0AhP","marks":64},{"name":"CWDjyRoSmq","marks":26},{"name":"Entj46ItNS","marks":96},{"name":"EiI7ug","marks":4},{"name":"efd","marks":83},{"name":"hNHN","marks":98},{"name":"jUAG0J","marks":52},{"name":"md64Jt4","marks":24},{"name":"n","marks":31},{"name":"FuEmCeOAx","marks":89},{"name":"bVqmMZP0bI","marks":47},{"name":"GQ8ile","marks":97},{"name":"tKjVM","marks":14},{"name":"Pl3mJn8","marks":43},{"name":"lSQkEj","marks":81},{"name":"AP2CQ","marks":48},{"name":"1RXToWpsCn","marks":21},{"name":"GwkMk2BtXk","marks":82},{"name":"Sn0QV","marks":52},{"name":"feT9","marks":51},{"name":"4YIEu","marks":61},{"name":"i","marks":37},{"name":"B","marks":61},{"name":"1kV","marks":93},{"name":"uZpH","marks":33},{"name":"9KDMqNgECV","marks":1},{"name":"kDIA5","marks":39},{"name":"6QzJaTf","marks":70},{"name":"krv3c4","marks":97},{"name":"VCBvZ78xLC","marks":46},{"name":"qpw","marks":1},{"name":"1qJp","marks":88},{"name":"As2By5f8","marks":87},{"name":"dkSkBE","marks":35},{"name":"OIFiBUB6","marks":55},{"name":"F","marks":8},{"name":"ICO3hEAj","marks":39},{"name":"Tqa","marks":79},{"name":"HO34SGvS","marks":69},{"name":"c1a1RqWR","marks":84},{"name":"c2HqN","marks":13},{"name":"Lo","marks":59},{"name":"d","marks":47}]
app = Flask(__name__)
@app.route('/api', methods=['GET'])
def get_marks():
    names = request.args.getlist('name')
    result = {"marks": [entry['marks'] for entry in marks_json_lis if entry['name'] in names]}
    return jsonify(result)
if __name__ == '__main__':  
    app.run(debug=True)